"""The Stocktake schema.

The whole database, in one revision. This is where a fresh install starts and
there is nothing before it.

**It is generated from `app/models.py`, not hand-written**, and it must stay
that way — `tests/test_migrations.py` asserts that autogenerate finds nothing
to change between the models and a database built from this file. That test
exists because the models and the migrations had silently drifted apart before
v1.0.0: eighteen `server_default`s and five foreign-key cascade rules differed,
and one of those differences would have deleted a person's trades out of a
shared portfolio when their account was removed. `tests/test_migrations.py`
is what keeps them together now.

So: change `models.py`, then regenerate rather than editing this file by hand.

Revision ID: 0001
Revises:
Create Date: 2026-08-11
"""

from __future__ import annotations

import sqlalchemy as sa
from alembic import op

from appkit import JSONType

revision = '0001'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fx_rate',
    sa.Column('pair', sa.String(length=6), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('rate', sa.Numeric(precision=12, scale=6), nullable=False),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('pair', 'date')
    )
    op.create_table('instrument',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticker', sa.String(length=12), nullable=False),
    sa.Column('exchange', sa.String(length=12), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('asset_class', sa.String(length=10), nullable=False),
    sa.Column('drp', sa.Boolean(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('yahoo_symbol', sa.String(length=20), nullable=True),
    sa.Column('note', sa.String(length=400), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('exchange', 'ticker')
    )
    op.create_table('login_attempt',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('ip', sa.String(length=45), nullable=False),
    sa.Column('success', sa.Boolean(), server_default=sa.false(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('login_attempt', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_login_attempt_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_login_attempt_email'), ['email'], unique=False)

    op.create_table('portfolio',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('reporting_currency', sa.String(length=3), server_default='AUD', nullable=False),
    sa.Column('jurisdiction', sa.String(length=2), server_default='AU', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('public_id', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.true(), nullable=False),
    sa.Column('is_admin', sa.Boolean(), server_default=sa.false(), nullable=False),
    sa.Column('must_change_password', sa.Boolean(), server_default=sa.false(), nullable=False),
    sa.Column('totp_secret', sa.String(length=64), nullable=True),
    sa.Column('totp_enabled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('theme', sa.String(length=8), server_default='auto', nullable=False),
    sa.Column('accent', sa.String(length=8), server_default='blue', nullable=False),
    sa.Column('nav_style', sa.String(length=8), server_default='both', nullable=False),
    sa.Column('nav_hidden', JSONType, nullable=True),
    sa.Column('theme_colors', JSONType, nullable=True),
    sa.Column('charts_seeded', sa.Boolean(), server_default=sa.false(), nullable=False),
    sa.Column('chart_layout', JSONType, nullable=True),
    sa.Column('dashboard_columns', JSONType, nullable=True),
    sa.Column('display_currency', sa.String(length=3), nullable=True),
    sa.Column('recovery_codes_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('public_id', name='uq_user_public_id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_user_public_id'), ['public_id'], unique=False)

    op.create_table('api_key',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('portfolio_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('key_hash', sa.String(length=64), nullable=False),
    sa.Column('prefix', sa.String(length=16), nullable=False),
    sa.Column('scopes', sa.String(length=32), server_default='read', nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolio.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('api_key', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_api_key_key_hash'), ['key_hash'], unique=True)
        batch_op.create_index(batch_op.f('ix_api_key_portfolio_id'), ['portfolio_id'], unique=False)

    op.create_table('holding_pref',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('portfolio_id', sa.Integer(), nullable=False),
    sa.Column('instrument_id', sa.Integer(), nullable=False),
    sa.Column('drp', sa.Boolean(), server_default=sa.false(), nullable=False),
    sa.Column('note', sa.String(length=400), nullable=True),
    sa.ForeignKeyConstraint(['instrument_id'], ['instrument.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolio.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('holding_pref', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_holding_pref_instrument_id'), ['instrument_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_holding_pref_portfolio_id'), ['portfolio_id'], unique=False)
        batch_op.create_index('uq_pref_portfolio_instrument', ['portfolio_id', 'instrument_id'], unique=True)

    op.create_table('investment_plan',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('portfolio_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('interval_days', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('brokerage', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('active', sa.Boolean(), server_default=sa.true(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolio.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('investment_plan', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_investment_plan_portfolio_id'), ['portfolio_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_investment_plan_user_id'), ['user_id'], unique=False)

    op.create_table('market_dividend',
    sa.Column('instrument_id', sa.Integer(), nullable=False),
    sa.Column('ex_date', sa.Date(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('source', sa.String(length=20), server_default='yfinance', nullable=False),
    sa.ForeignKeyConstraint(['instrument_id'], ['instrument.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('instrument_id', 'ex_date')
    )
    op.create_table('portfolio_member',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('portfolio_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=8), server_default='member', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("role IN ('owner','member','viewer')", name='member_role'),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolio.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('portfolio_id', 'user_id', name='uq_member_portfolio_user')
    )
    with op.batch_alter_table('portfolio_member', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_portfolio_member_portfolio_id'), ['portfolio_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_portfolio_member_user_id'), ['user_id'], unique=False)

    op.create_table('price',
    sa.Column('instrument_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('close', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('provisional', sa.Boolean(), server_default=sa.false(), nullable=False),
    sa.ForeignKeyConstraint(['instrument_id'], ['instrument.id'], ),
    sa.PrimaryKeyConstraint('instrument_id', 'date')
    )
    op.create_table('recovery_code',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('code_hash', sa.String(length=64), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('recovery_code', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_recovery_code_code_hash'), ['code_hash'], unique=False)
        batch_op.create_index(batch_op.f('ix_recovery_code_user_id'), ['user_id'], unique=False)

    op.create_table('saved_chart',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('portfolio_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('spec', JSONType, nullable=False),
    sa.Column('template_key', sa.String(length=40), nullable=True),
    sa.Column('position', sa.Integer(), server_default='0', nullable=False),
    sa.Column('width', sa.String(length=8), server_default='half', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolio.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('saved_chart', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_saved_chart_portfolio_id'), ['portfolio_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_saved_chart_user_id'), ['user_id'], unique=False)

    op.create_table('trade',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('portfolio_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('instrument_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('time', sa.Time(), nullable=True),
    sa.Column('type', sa.String(length=4), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('brokerage', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('fx_rate', sa.Numeric(precision=12, scale=6), nullable=True),
    sa.Column('note', sa.String(length=400), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("type IN ('buy','sell','drp')", name='trade_type'),
    sa.CheckConstraint('quantity > 0', name='trade_qty_positive'),
    sa.ForeignKeyConstraint(['instrument_id'], ['instrument.id'], ),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolio.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('trade', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_trade_date'), ['date'], unique=False)
        batch_op.create_index(batch_op.f('ix_trade_instrument_id'), ['instrument_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_trade_portfolio_id'), ['portfolio_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_trade_user_id'), ['user_id'], unique=False)

    op.create_table('user_session',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('active_portfolio_id', sa.Integer(), nullable=True),
    sa.Column('csrf_token', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ip', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=200), nullable=True),
    sa.Column('recovery_spent', sa.Boolean(), server_default=sa.false(), nullable=False),
    sa.Column('awaiting_totp', sa.Boolean(), server_default=sa.false(), nullable=False),
    sa.ForeignKeyConstraint(['active_portfolio_id'], ['portfolio.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user_session', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_session_expires_at'), ['expires_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_session_token_hash'), ['token_hash'], unique=True)
        batch_op.create_index(batch_op.f('ix_user_session_user_id'), ['user_id'], unique=False)

    op.create_table('webauthn_credential',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('credential_id', sa.String(length=255), nullable=False),
    sa.Column('public_key', sa.String(length=1024), nullable=False),
    sa.Column('sign_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('transports', sa.String(length=80), nullable=True),
    sa.Column('name', sa.String(length=80), nullable=True),
    sa.Column('rp_id', sa.String(length=253), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('credential_id', name='uq_webauthn_credential_id')
    )
    with op.batch_alter_table('webauthn_credential', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_webauthn_credential_credential_id'), ['credential_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_webauthn_credential_user_id'), ['user_id'], unique=False)

    op.create_table('dividend',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('portfolio_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('instrument_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('cash_amount', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.Column('fx_rate', sa.Numeric(precision=12, scale=6), nullable=True),
    sa.Column('franking_credits', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('residual_carried', sa.Numeric(precision=14, scale=4), nullable=True),
    sa.Column('reinvest_trade_id', sa.Integer(), nullable=True),
    sa.Column('note', sa.String(length=400), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['instrument_id'], ['instrument.id'], ),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolio.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reinvest_trade_id'], ['trade.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('reinvest_trade_id')
    )
    with op.batch_alter_table('dividend', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_dividend_date'), ['date'], unique=False)
        batch_op.create_index(batch_op.f('ix_dividend_instrument_id'), ['instrument_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_dividend_portfolio_id'), ['portfolio_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_dividend_user_id'), ['user_id'], unique=False)

    op.create_table('investment_plan_entry',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('plan_id', sa.Integer(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('instrument_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['instrument_id'], ['instrument.id'], ),
    sa.ForeignKeyConstraint(['plan_id'], ['investment_plan.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('plan_id', 'position', name='uq_plan_entry_position')
    )
    with op.batch_alter_table('investment_plan_entry', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_investment_plan_entry_plan_id'), ['plan_id'], unique=False)

    op.create_table('planned_purchase',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('portfolio_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('due_date', sa.Date(), nullable=False),
    sa.Column('instrument_id', sa.Integer(), nullable=False),
    sa.Column('plan_entry_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=8), nullable=False),
    sa.Column('trade_id', sa.Integer(), nullable=True),
    sa.Column('note', sa.String(length=200), nullable=True),
    sa.CheckConstraint("status IN ('planned','done','skipped')", name='plan_status'),
    sa.ForeignKeyConstraint(['instrument_id'], ['instrument.id'], ),
    sa.ForeignKeyConstraint(['plan_entry_id'], ['investment_plan_entry.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolio.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['trade_id'], ['trade.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('planned_purchase', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_planned_purchase_due_date'), ['due_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_planned_purchase_portfolio_id'), ['portfolio_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_planned_purchase_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('planned_purchase', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_planned_purchase_user_id'))
        batch_op.drop_index(batch_op.f('ix_planned_purchase_portfolio_id'))
        batch_op.drop_index(batch_op.f('ix_planned_purchase_due_date'))

    op.drop_table('planned_purchase')
    with op.batch_alter_table('investment_plan_entry', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_investment_plan_entry_plan_id'))

    op.drop_table('investment_plan_entry')
    with op.batch_alter_table('dividend', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_dividend_user_id'))
        batch_op.drop_index(batch_op.f('ix_dividend_portfolio_id'))
        batch_op.drop_index(batch_op.f('ix_dividend_instrument_id'))
        batch_op.drop_index(batch_op.f('ix_dividend_date'))

    op.drop_table('dividend')
    with op.batch_alter_table('webauthn_credential', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_webauthn_credential_user_id'))
        batch_op.drop_index(batch_op.f('ix_webauthn_credential_credential_id'))

    op.drop_table('webauthn_credential')
    with op.batch_alter_table('user_session', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_session_user_id'))
        batch_op.drop_index(batch_op.f('ix_user_session_token_hash'))
        batch_op.drop_index(batch_op.f('ix_user_session_expires_at'))

    op.drop_table('user_session')
    with op.batch_alter_table('trade', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_trade_user_id'))
        batch_op.drop_index(batch_op.f('ix_trade_portfolio_id'))
        batch_op.drop_index(batch_op.f('ix_trade_instrument_id'))
        batch_op.drop_index(batch_op.f('ix_trade_date'))

    op.drop_table('trade')
    with op.batch_alter_table('saved_chart', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_saved_chart_user_id'))
        batch_op.drop_index(batch_op.f('ix_saved_chart_portfolio_id'))

    op.drop_table('saved_chart')
    with op.batch_alter_table('recovery_code', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_recovery_code_user_id'))
        batch_op.drop_index(batch_op.f('ix_recovery_code_code_hash'))

    op.drop_table('recovery_code')
    op.drop_table('price')
    with op.batch_alter_table('portfolio_member', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_portfolio_member_user_id'))
        batch_op.drop_index(batch_op.f('ix_portfolio_member_portfolio_id'))

    op.drop_table('portfolio_member')
    op.drop_table('market_dividend')
    with op.batch_alter_table('investment_plan', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_investment_plan_user_id'))
        batch_op.drop_index(batch_op.f('ix_investment_plan_portfolio_id'))

    op.drop_table('investment_plan')
    with op.batch_alter_table('holding_pref', schema=None) as batch_op:
        batch_op.drop_index('uq_pref_portfolio_instrument')
        batch_op.drop_index(batch_op.f('ix_holding_pref_portfolio_id'))
        batch_op.drop_index(batch_op.f('ix_holding_pref_instrument_id'))

    op.drop_table('holding_pref')
    with op.batch_alter_table('api_key', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_api_key_portfolio_id'))
        batch_op.drop_index(batch_op.f('ix_api_key_key_hash'))

    op.drop_table('api_key')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_public_id'))
        batch_op.drop_index(batch_op.f('ix_user_email'))

    op.drop_table('user')
    op.drop_table('portfolio')
    with op.batch_alter_table('login_attempt', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_login_attempt_email'))
        batch_op.drop_index(batch_op.f('ix_login_attempt_created_at'))

    op.drop_table('login_attempt')
    op.drop_table('instrument')
    op.drop_table('fx_rate')
    # ### end Alembic commands ###
