"""Show trade times on the viewer's clock.

Adds `user.times_in`: which clock a trade's time is DISPLAYED on. Storage is
untouched and stays the exchange's own clock, because `models.trade_order`
sequences a day's trades for FIFO and a stored time that moved with the viewer
would reorder a same-day buy and sell — which is a tax figure.

Generated by autogenerate from models.py, not written by hand — see
0001_initial and tests/test_migrations.py.

Revision ID: 0002
Revises: 0001
Create Date: 2026-08-23
"""

from __future__ import annotations

import sqlalchemy as sa
from alembic import op

revision = '0002'
down_revision = '0001'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # batch_alter_table because SQLite cannot ALTER a column in place; alembic
    # rebuilds the table instead. server_default so rows that already exist get
    # a value rather than failing the NOT NULL.
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('times_in', sa.String(length=6), server_default='market', nullable=False))



def downgrade() -> None:
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('times_in')

